name: C Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klónozása
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. A szükséges csomagok telepítése
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3. Fordítás
      - name: Compile C program
        run: gcc -o hundredtest hundredtest.c

      # 4. Futás ellenőrzése (opcionális)
      - name: Run program
        run: ./hundredtest

