name: C Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klónozása
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. A szükséges csomagok telepítése
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3. Fordítás a futtatható programhoz
      - name: Compile main program
        run: gcc -o hundredtest hundredtest.c

      # 4. Fordítás a tesztekhez
      - name: Compile tests
        run: gcc -DTESTING test_hundredtest.c hundredtest.c -o test_hundredtest

      # 5. Tesztek futtatása
      - name: Run tests
        run: ./test_hundredtest
