name: C Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository klónozása
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. A szükséges csomagok telepítése
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3. Fordítás az eredeti programhoz
      - name: Compile hundredtest
        run: gcc -o hundredtest hundredtest.c

      # 4. Fordítás a tesztfájlhoz
      - name: Compile tests
        run: gcc -o test_hundredtest hundredtest.c test_hundredtest.c

      # 5. Tesztek futtatása
      - name: Run tests
        run: ./test_hundredtest
